### ISSUE TITLE
Erroded gate pearl

### ISSUE THREAD

**Issue by Coen-Townson** [Shadows-of-Fire/GatewaysToEternity#35] opened 2023-08-27 09:51 UTC
I received an erroded gate pearl in RADS 2 from the Meet Your Fight! - Any Gate Pearl quest. I'm in a team and my friend completed the quest first and got a skeleton gate I just completed it by association, not sure if that's the difference but seems to be

**Comment by Shadows-of-Fire** [comment] 2023-08-27 09:55
This is likely the same root cause of https://github.com/Shadows-of-Fire/GatewaysToEternity/issues/29 which was resolved in a ModernFix update.

**Closed as not planned by Shadows-of-Fire** 2023-08-27 09:55 UTC
