### ISSUE TITLE
Gates causing world corruption on multiplayer.

### ISSUE THREAD

**Issue by RykerQuest** [Shadows-of-Fire/GatewaysToEternity#4] opened 2022-08-10 23:35 UTC
Some gates, mainly the ghast gate, causes world corruption,

**Comment by Shadows-of-Fire** [comment] 2022-08-10 23:57
A crash report or similar is required for bug reports

**Comment by Shadows-of-Fire** [comment] 2022-08-11 05:56
Closing as duplicate of #3 (probably)

**Closed by Shadows-of-Fire** 2022-08-11 05:56 UTC
